<a href="https://colab.research.google.com/github/iqrasarwar/ComputerVision/blob/main/mids.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
arr = np.array([7,2,9.9,True,'s'])

# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  1
Shape of array:  (5,)
Size of array:  5
Array stores elements of type:  <U32


In [15]:
rr_constant = np.full((2,2), 5)  # Create a constant array
print(rr_constant)    
rr_constant[0][0] = 0
print(rr_constant) 
rr_constant = np.full((3,3),6)
print(rr_constant) 

[[5 5]
 [5 5]]
[[0 5]
 [5 5]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [13]:
arr_of_ones = np.zeros((3,3))+2   # Create an array of all ones
print(arr_of_ones)   
arr_of_ones[0][0] = 0
print(arr_of_ones) 

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[0. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [17]:
identity_matrix = np.eye(10)         # Create a 3x3 of identity matrix
print(identity_matrix)  

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
random_arr = np.random.random((3,3))  # Create an array filled with random values
print(random_arr)     

[[0.41675107 0.3047007  0.28589301]
 [0.54258585 0.04693406 0.98004828]
 [0.325236   0.21035454 0.47851547]]


In [22]:
x = np.array([[4,9,16],
              [4,9,16]])

y = np.array([[4,9,16],
              [7,10,16]])

print(x + y) # Elementwise sum; both produce the array
print(np.add(x, y))

print(x - y) # Elementwise difference; both produce the array
print(np.subtract(x, y))

print(x * y) # Elementwise product; both produce the array
print(np.multiply(x, y))

print(x / y) # Elementwise division; both produce the array
print(np.divide(x, y))

print(np.sqrt(x)) # Elementwise square root; produces the array

[[ 8 18 32]
 [11 19 32]]
[[ 8 18 32]
 [11 19 32]]
[[ 0  0  0]
 [-3 -1  0]]
[[ 0  0  0]
 [-3 -1  0]]
[[ 16  81 256]
 [ 28  90 256]]
[[ 16  81 256]
 [ 28  90 256]]
[[1.         1.         1.        ]
 [0.57142857 0.9        1.        ]]
[[1.         1.         1.        ]
 [0.57142857 0.9        1.        ]]
[[2. 3. 4.]
 [2. 3. 4.]]


In [23]:
mu = 0.5
sigma = 0.5

rand_normal_arr1 = np.random.normal(mu, sigma, size=(4,4)) # generate random numbers with mean 0.5 and sigma 1
print(rand_normal_arr1)

[[ 0.22865894 -0.153394    0.47747444  1.17174272]
 [-0.00615774  0.015736    0.7379172   0.33684553]
 [ 0.64792009  1.70027533  0.29704635  0.33536745]
 [ 1.04716337 -0.38651547  0.94831007  0.49092201]]


In [26]:
rand_normal_arr = np.random.normal(size=(4,)) # random numbers from normal distribution
print(rand_normal_arr)

[-0.64917248 -1.3505472  -0.75643245  0.36747665]


In [28]:
print(np.random.randint(1, [3, 5, 10]))

[1 3 5]


In [31]:
np.random.randint([1, 5, 7], 10)

array([4, 9, 7])

In [32]:
np.random.randint(5, size=(2, 4))

array([[1, 2, 4, 2],
       [4, 3, 3, 3]])