<a href="https://colab.research.google.com/github/iqrasarwar/ComputerVision/blob/main/mids.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
arr = np.array([7,2,9.9,True,'s'])

# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  1
Shape of array:  (5,)
Size of array:  5
Array stores elements of type:  <U32


In [15]:
rr_constant = np.full((2,2), 5)  # Create a constant array
print(rr_constant)    
rr_constant[0][0] = 0
print(rr_constant) 
rr_constant = np.full((3,3),6)
print(rr_constant) 

[[5 5]
 [5 5]]
[[0 5]
 [5 5]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [13]:
arr_of_ones = np.zeros((3,3))+2   # Create an array of all ones
print(arr_of_ones)   
arr_of_ones[0][0] = 0
print(arr_of_ones) 

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[0. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
